services:
    node:
        build:
            context: ..
            dockerfile: docker/node/Dockerfile

        volumes:
            - ..:/usr/src/app
            - node_modules:/usr/src/app/node_modules

        ports:
            - "51204:51204"

        stdin_open: true
        tty: true

volumes:
    node_modules:
